// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.one.note.noted.domain;

import java.lang.Integer;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.one.note.noted.domain.ChordPosition;
import org.springframework.stereotype.Component;

privileged aspect ChordPositionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ChordPositionDataOnDemand: @Component;
    
    private Random ChordPositionDataOnDemand.rnd = new SecureRandom();
    
    private List<ChordPosition> ChordPositionDataOnDemand.data;
    
    public ChordPosition ChordPositionDataOnDemand.getNewTransientChordPosition(String index) {
        ChordPosition obj = new ChordPosition();
        setChord(obj, index);
        setPos(obj, index);
        return obj;
    }
    
    public void ChordPositionDataOnDemand.setChord(ChordPosition obj, String index) {
        String chord = "chord_" + index;
        obj.setChord(chord);
    }
    
    public void ChordPositionDataOnDemand.setPos(ChordPosition obj, String pos) {
        obj.setPos(pos);
    }
    
    public ChordPosition ChordPositionDataOnDemand.getSpecificChordPosition(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ChordPosition obj = data.get(index);
        return ChordPosition.findChordPosition(obj.getId());
    }
    
    public ChordPosition ChordPositionDataOnDemand.getRandomChordPosition() {
        init();
        ChordPosition obj = data.get(rnd.nextInt(data.size()));
        return ChordPosition.findChordPosition(obj.getId());
    }
    
    public boolean ChordPositionDataOnDemand.modifyChordPosition(ChordPosition obj) {
        return false;
    }
    
    public void ChordPositionDataOnDemand.init() {
        data = ChordPosition.findChordPositionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ChordPosition' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.one.note.noted.domain.ChordPosition>();
        for (int i = 0; i < 10; i++) {
            ChordPosition obj = getNewTransientChordPosition(String.valueOf(i));
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
