// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.one.note.noted.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.one.note.noted.domain.SongEntry;
import org.one.note.noted.domain.Tablature;
import org.one.note.noted.domain.TablatureDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SongEntryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SongEntryDataOnDemand: @Component;
    
    private Random SongEntryDataOnDemand.rnd = new SecureRandom();
    
    private List<SongEntry> SongEntryDataOnDemand.data;
    
    @Autowired
    private TablatureDataOnDemand SongEntryDataOnDemand.tablatureDataOnDemand;
    
    public SongEntry SongEntryDataOnDemand.getNewTransientSongEntry(int index) {
        SongEntry obj = new SongEntry();
        setTablature(obj, index);
        return obj;
    }
    
    public void SongEntryDataOnDemand.setTablature(SongEntry obj, int index) {
        Tablature tablature = tablatureDataOnDemand.getRandomTablature();
        obj.setTablature(tablature);
    }
    
    public SongEntry SongEntryDataOnDemand.getSpecificSongEntry(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        SongEntry obj = data.get(index);
        return SongEntry.findSongEntry(obj.getId());
    }
    
    public SongEntry SongEntryDataOnDemand.getRandomSongEntry() {
        init();
        SongEntry obj = data.get(rnd.nextInt(data.size()));
        return SongEntry.findSongEntry(obj.getId());
    }
    
    public boolean SongEntryDataOnDemand.modifySongEntry(SongEntry obj) {
        return false;
    }
    
    public void SongEntryDataOnDemand.init() {
        data = SongEntry.findSongEntryEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'SongEntry' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.one.note.noted.domain.SongEntry>();
        for (int i = 0; i < 10; i++) {
            SongEntry obj = getNewTransientSongEntry(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
