// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.one.note.noted.domain;

import java.lang.Integer;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.one.note.noted.domain.UserAccount;
import org.one.note.noted.domain.UserAccountDataOnDemand;
import org.one.note.noted.domain.VideoEntry;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VideoEntryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VideoEntryDataOnDemand: @Component;
    
    private Random VideoEntryDataOnDemand.rnd = new SecureRandom();
    
    private List<VideoEntry> VideoEntryDataOnDemand.data;
    
    @Autowired
    private UserAccountDataOnDemand VideoEntryDataOnDemand.userAccountDataOnDemand;
    
    public VideoEntry VideoEntryDataOnDemand.getNewTransientVideoEntry(int index) {
        VideoEntry obj = new VideoEntry();
        setAddedAt(obj, index);
        setAuthor(obj, index);
        setDownVotes(obj, index);
        setThumbnailUrl(obj, index);
        setUpVotes(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void VideoEntryDataOnDemand.setAddedAt(VideoEntry obj, int index) {
        Date addedAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setAddedAt(addedAt);
    }
    
    public void VideoEntryDataOnDemand.setAuthor(VideoEntry obj, int index) {
        UserAccount author = userAccountDataOnDemand.getRandomUserAccount();
        obj.setAuthor(author);
    }
    
    public void VideoEntryDataOnDemand.setDownVotes(VideoEntry obj, int index) {
        Integer downVotes = new Integer(index);
        obj.setDownVotes(downVotes);
    }
    
    public void VideoEntryDataOnDemand.setThumbnailUrl(VideoEntry obj, int index) {
        String thumbnailUrl = "thumbnailUrl_" + index;
        obj.setThumbnailUrl(thumbnailUrl);
    }
    
    public void VideoEntryDataOnDemand.setUpVotes(VideoEntry obj, int index) {
        Integer upVotes = new Integer(index);
        obj.setUpVotes(upVotes);
    }
    
    public void VideoEntryDataOnDemand.setUrl(VideoEntry obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public VideoEntry VideoEntryDataOnDemand.getSpecificVideoEntry(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        VideoEntry obj = data.get(index);
        return VideoEntry.findVideoEntry(obj.getId());
    }
    
    public VideoEntry VideoEntryDataOnDemand.getRandomVideoEntry() {
        init();
        VideoEntry obj = data.get(rnd.nextInt(data.size()));
        return VideoEntry.findVideoEntry(obj.getId());
    }
    
    public boolean VideoEntryDataOnDemand.modifyVideoEntry(VideoEntry obj) {
        return false;
    }
    
    public void VideoEntryDataOnDemand.init() {
        data = VideoEntry.findVideoEntryEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'VideoEntry' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.one.note.noted.domain.VideoEntry>();
        for (int i = 0; i < 10; i++) {
            VideoEntry obj = getNewTransientVideoEntry(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
