// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.one.note.noted.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.one.note.noted.domain.VideoEntryDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VideoEntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VideoEntryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VideoEntryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: VideoEntryIntegrationTest: @Transactional;
    
    @Autowired
    private VideoEntryDataOnDemand VideoEntryIntegrationTest.dod;
    
    @Test
    public void VideoEntryIntegrationTest.testCountVideoEntrys() {
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", dod.getRandomVideoEntry());
        long count = org.one.note.noted.domain.VideoEntry.countVideoEntrys();
        org.junit.Assert.assertTrue("Counter for 'VideoEntry' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VideoEntryIntegrationTest.testFindVideoEntry() {
        org.one.note.noted.domain.VideoEntry obj = dod.getRandomVideoEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to provide an identifier", id);
        obj = org.one.note.noted.domain.VideoEntry.findVideoEntry(id);
        org.junit.Assert.assertNotNull("Find method for 'VideoEntry' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'VideoEntry' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VideoEntryIntegrationTest.testFindAllVideoEntrys() {
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", dod.getRandomVideoEntry());
        long count = org.one.note.noted.domain.VideoEntry.countVideoEntrys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'VideoEntry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.one.note.noted.domain.VideoEntry> result = org.one.note.noted.domain.VideoEntry.findAllVideoEntrys();
        org.junit.Assert.assertNotNull("Find all method for 'VideoEntry' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'VideoEntry' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VideoEntryIntegrationTest.testFindVideoEntryEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", dod.getRandomVideoEntry());
        long count = org.one.note.noted.domain.VideoEntry.countVideoEntrys();
        if (count > 20) count = 20;
        java.util.List<org.one.note.noted.domain.VideoEntry> result = org.one.note.noted.domain.VideoEntry.findVideoEntryEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'VideoEntry' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'VideoEntry' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VideoEntryIntegrationTest.testFlush() {
        org.one.note.noted.domain.VideoEntry obj = dod.getRandomVideoEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to provide an identifier", id);
        obj = org.one.note.noted.domain.VideoEntry.findVideoEntry(id);
        org.junit.Assert.assertNotNull("Find method for 'VideoEntry' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVideoEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'VideoEntry' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VideoEntryIntegrationTest.testMerge() {
        org.one.note.noted.domain.VideoEntry obj = dod.getRandomVideoEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to provide an identifier", id);
        obj = org.one.note.noted.domain.VideoEntry.findVideoEntry(id);
        boolean modified =  dod.modifyVideoEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.one.note.noted.domain.VideoEntry merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'VideoEntry' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VideoEntryIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", dod.getRandomVideoEntry());
        org.one.note.noted.domain.VideoEntry obj = dod.getNewTransientVideoEntry(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'VideoEntry' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'VideoEntry' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VideoEntryIntegrationTest.testRemove() {
        org.one.note.noted.domain.VideoEntry obj = dod.getRandomVideoEntry();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'VideoEntry' failed to provide an identifier", id);
        obj = org.one.note.noted.domain.VideoEntry.findVideoEntry(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'VideoEntry' with identifier '" + id + "'", org.one.note.noted.domain.VideoEntry.findVideoEntry(id));
    }
    
}
